spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cobol_db_example}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
